# Generated by Django 5.0.7 on 2024-08-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='qr_code_path',
        ),
        migrations.RemoveField(
            model_name='section',
            name='qr_code_path',
        ),
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
