# Generated by Django 5.0.7 on 2024-08-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_remove_lecture_qr_code_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depcourses', to='attend.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depcourses', to='attend.department')),
                ('dofaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depcourses', to='attend.dofaa')),
            ],
        ),
    ]
