# Generated by Django 5.0.7 on 2024-08-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_remove_lecture_course_remove_section_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='DepCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='attend.depcourse'),
        ),
        migrations.AlterField(
            model_name='section',
            name='DepCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attend.depcourse'),
        ),
    ]
