# Generated by Django 5.0.7 on 2024-08-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0005_alter_lecture_depcourse_alter_section_depcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depcourse',
            name='dofaa',
        ),
        migrations.AddField(
            model_name='depcourse',
            name='academic_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dofaa',
            name='academic_year',
            field=models.SmallIntegerField(default=1),
        ),
    ]
