# Generated by Django 5.0.7 on 2024-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0006_remove_depcourse_dofaa_depcourse_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
