# Generated by Django 5.1.1 on 2024-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0008_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
