# Generated by Django 5.1.1 on 2024-10-07 00:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0010_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='os_family',
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('students', models.CharField(blank=True, max_length=150, null=True)),
                ('session_type', models.CharField(choices=[('Lec', 'Lec'), ('Sec', 'Sec')], default='Lec', max_length=3)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('subject_name', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.CharField(blank=True, max_length=150, null=True)),
                ('pic_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialevents', to='attend.college')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialevents', to='attend.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialevents', to='attend.doctor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialevents', to='attend.room')),
            ],
        ),
    ]
