# Generated by Django 5.0.7 on 2024-10-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0011_remove_student_os_family_specialevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialevent",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
