# Generated by Django 5.0.7 on 2024-10-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attend", "0012_specialevent_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialevent",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
