# Generated by Django 5.1.1 on 2024-10-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0013_alter_specialevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='depcourse',
            constraint=models.UniqueConstraint(fields=('course', 'department', 'academic_year'), name='unique_dep_course_year'),
        ),
    ]
