# Generated by Django 5.1.1 on 2024-10-26 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0014_alter_course_name_depcourse_unique_dep_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
