# Generated by Django 5.1.1 on 2024-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0015_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
