# Generated by Django 5.1.1 on 2024-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0016_lecture_end_date_section_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
