# Generated by Django 5.0.7 on 2025-05-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0018_officescreen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dofaa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='OfficeScreen',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
