# Generated by Django 5.2.1 on 2025-05-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0019_remove_student_classs_remove_student_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=255, null=True)),
                ('text_2', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='attend.doctor')),
            ],
        ),
    ]
