# Generated by Django 5.2.1 on 2025-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0020_officescreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
